CREATE TABLE `rule` (
                        `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
                        `pid` int(11) unsigned NOT NULL DEFAULT '0',
                        `path` varchar(255) NOT NULL DEFAULT '',
                        `name` varchar(30) NOT NULL DEFAULT '' COMMENT '规则名称',
                        `type` enum('page','api') NOT NULL DEFAULT 'api' COMMENT '1-页面|2-操作',
                        `method` enum('GET','POST','PUT','DELETE') DEFAULT NULL COMMENT '接口请求方式',
                        `permission_id` varchar(30) DEFAULT NULL,
                        `operation` varchar(30) DEFAULT NULL COMMENT '操作标识',
                        `service_router` text COMMENT '接口路由',
                        `client_router` varchar(100) DEFAULT NULL COMMENT '客户端路由',
                        `client_route_name` varchar(100) DEFAULT NULL COMMENT '客户端路由名称',
                        `client_route_alias` varchar(100) DEFAULT NULL COMMENT '客户端路由别名',
                        `icon` varchar(100) DEFAULT NULL,
                        `sort` tinyint(255) unsigned NOT NULL DEFAULT '0',
                        PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='权限规则';

=@=@=@=@=@=

INSERT INTO `rule` (`id`, `pid`, `path`, `name`, `type`, `method`, `permission_id`, `operation`, `service_router`, `client_router`, `client_route_name`, `client_route_alias`, `icon`, `sort`)
VALUES
	(1, 0, ',1', 'Root', 'page', NULL, NULL, '', NULL, 'Root', NULL, NULL, NULL, 0),
	(2, 1, ',1,2', '工作台', 'page', NULL, 'Home', '', NULL, 'Home', NULL, NULL, NULL, 0),
	(3, 1, ',1,3', '系统维护', 'page', NULL, 'System', NULL, NULL, 'System', NULL, NULL, NULL, 0),
	(4, 3, '0,1,3,4', '权限维护', 'page', NULL, 'Rule', '', '/l/rule', 'Rule', NULL, NULL, NULL, 0),
	(5, 4, '0,1,3,4,5', '规则详情', 'api', 'GET', NULL, 'detail', '/l/rule/{id}', NULL, NULL, NULL, NULL, 0),
	(6, 4, '0,1,3,4,6', '新建规则', 'api', 'POST', NULL, 'create', '/l/rule', NULL, NULL, NULL, NULL, 0),
	(7, 4, '0,1,3,7', '修改规则', 'api', 'PUT', NULL, 'update', '/l/rule/{id}', NULL, NULL, NULL, NULL, 0),
	(8, 4, '0,1,3,8', '删除规则', 'api', 'DELETE', NULL, 'delete', '/l/rule/{id}', NULL, NULL, NULL, NULL, 0),
	(10, 3, '0,1,3,10', '账号维护', 'page', 'GET', NULL, NULL, '/l/user', 'User', NULL, NULL, NULL, 0),
	(11, 10, '0,1,3,10,11', '账号详情', 'api', 'GET', NULL, 'read', '/l/user/{id}', NULL, NULL, NULL, NULL, 0),
	(12, 10, '0,1,3,10,12', '新建账号', 'api', 'POST', NULL, 'create', '/l/user', NULL, NULL, NULL, NULL, 0),
	(13, 10, '0,1,3,10,13', '修改账号', 'api', 'PUT', NULL, 'update', '/l/user/{id}', NULL, NULL, NULL, NULL, 0),
	(14, 10, '0,1,3,10,14', '删除账号', 'api', 'DELETE', NULL, 'delete', '/l/user/{id}', NULL, NULL, NULL, NULL, 0),
	(15, 3, '0,1,3,15', '组织成员', 'page', 'GET', NULL, NULL, NULL, 'OrgMember', NULL, NULL, NULL, 0),
	(16, 15, '0,1,3,15,16', '组织用户', 'page', 'GET', NULL, NULL, '/l/account', 'Account', NULL, NULL, NULL, 0),
	(17, 15, '0,1,3,15,17', '权限集', 'page', 'GET', NULL, NULL, '/l/role', 'Role', NULL, NULL, NULL, 0),
	(18, 17, '0,1,3,15,17,18', '角色详情', 'api', 'GET', NULL, 'read', '/l/role/{id}', NULL, NULL, NULL, NULL, 0),
	(19, 17, '0,1,3,15,17,19', '新建角色', 'api', 'POST', NULL, 'create', '/l/role', NULL, NULL, NULL, NULL, 0),
	(20, 17, '0,1,3,15,17,20', '修改角色', 'api', 'PUT', NULL, 'update', '/l/role/{id}', NULL, NULL, NULL, NULL, 0),
	(21, 17, '0,1,3,15,17,21', '删除角色', 'api', 'DELETE', NULL, 'delete', '/l/role/{id}', NULL, NULL, NULL, NULL, 0),
	(22, 16, '0,1,3,15,16,22', '用户详情', 'api', 'GET', NULL, 'read', '/l/account/{id}', NULL, NULL, NULL, NULL, 0),
	(23, 16, '0,1,3,15,16,23', '新建用户', 'api', 'POST', NULL, 'create', '/l/account', NULL, NULL, NULL, NULL, 0),
	(24, 16, '0,1,3,15,16,24', '修改用户', 'api', 'PUT', NULL, 'update', '/l/account/{id}', NULL, NULL, NULL, NULL, 0),
	(25, 16, '0,1,3,15,16,25', '删除用户', 'api', 'DELETE', NULL, 'delete', '/l/account/{id}', NULL, NULL, NULL, NULL, 0),
	(26, 3, '0,1,3,26', '组织维护', 'page', 'GET', NULL, NULL, '', 'Org', NULL, NULL, NULL, 0),
	(27, 26, '0,1,3,26,27', '组织列表', 'api', 'GET', NULL, 'index', '/l/organization', NULL, NULL, NULL, NULL, 0),
	(28, 26, '0,1,3,26,28', '组织详情', 'api', 'GET', NULL, 'read', '/l/organization/{id}', NULL, NULL, NULL, NULL, 0),
	(29, 26, '0,1,3,26,29', '新建组织', 'api', 'POST', NULL, 'create', '/l/organization', NULL, NULL, NULL, NULL, 0),
	(30, 26, '0,1,3,26,30', '修改组织', 'api', 'PUT', NULL, 'update', '/l/organization/{id}', NULL, NULL, NULL, NULL, 0),
	(31, 26, '0,1,3,26,31', '删除组织', 'api', 'DELETE', NULL, 'delete', '/l/organization/{id}', NULL, NULL, NULL, NULL, 0),
	(32, 3, '0,1,3,32', '字典维护', 'page', 'GET', NULL, NULL, '/l/dictionary', 'Dictionary', NULL, NULL, NULL, 0),
	(33, 32, '0,1,3,32,33', '字典详情', 'api', 'GET', NULL, 'read', '/l/dictionary/{id}', NULL, NULL, NULL, NULL, 0),
	(34, 32, '0,1,3,32,34', '新建字典', 'api', 'POST', NULL, 'create', '/l/dictionary', NULL, NULL, NULL, NULL, 0),
	(35, 32, '0,1,3,32,35', '修改字典', 'api', 'PUT', NULL, 'update', '/l/dictionary/{id}', NULL, NULL, NULL, NULL, 0),
	(36, 32, '0,1,3,32,36', '删除字典', 'api', 'DELETE', NULL, 'delete', '/l/dictionary/{id}', NULL, NULL, NULL, NULL, 0),
	(37, 1, '0,1,37', 'CMS', 'page', 'GET', NULL, NULL, NULL, 'CMS', NULL, NULL, NULL, 0),
	(38, 37, '0,1,37,38', '广告', 'page', 'GET', NULL, NULL, '/ad', 'Ad', NULL, NULL, NULL, 0),
	(39, 37, '0,1,37,39', '文章动态', 'page', 'GET', NULL, NULL, '/msite/category\n/msite/category/{id}\nPATCH:/msite/category\nGET:/msite/news-top\nPOST:/msite/news-top', 'News', NULL, NULL, NULL, 0),
	(40, 39, '0,1,37,39,40', '动态列表', 'api', 'GET', NULL, 'index', '/msite/news', NULL, NULL, NULL, NULL, 0),
	(41, 39, '0,1,37,39,41', '动态详情', 'api', 'GET', NULL, 'read', '/msite/news/{id}', NULL, NULL, NULL, NULL, 0),
	(42, 39, '0,1,37,39,42', '发布动态', 'api', 'POST', NULL, 'create', '/msite/news', NULL, NULL, NULL, NULL, 0),
	(43, 39, '0,1,37,39,43', '修改动态', 'api', 'PUT', NULL, 'update', '/msite/news/{id}', NULL, NULL, NULL, NULL, 0),
	(44, 39, '0,1,37,39,44', '删除动态', 'api', 'DELETE', NULL, 'delete', '/msite/news/{id}', NULL, NULL, NULL, NULL, 0),
	(45, 15, '0,1,3,15,45', '部门', 'page', 'GET', NULL, NULL, '/l/department', 'Department', NULL, NULL, NULL, 0),
	(46, 45, '0,1,3,15,45,46', '部门详情', 'api', 'GET', NULL, 'read', '/l/department/{id}', NULL, NULL, NULL, NULL, 0),
	(47, 45, '0,1,3,15,45,47', '新建部门', 'api', 'POST', NULL, 'create', '/l/department', NULL, NULL, NULL, NULL, 0),
	(48, 45, '0,1,3,15,45,48', '修改部门', 'api', 'PUT', NULL, 'update', '/l/department/{id}', NULL, NULL, NULL, NULL, 0),
	(49, 45, '0,1,3,15,45,49', '删除部门', 'api', 'DELETE', NULL, 'delete', '/l/department/{id}', NULL, NULL, NULL, NULL, 0);
