INSERT INTO `rule` (`id`, `pid`, `path`, `name`, `type`, `method`, `permission_id`, `operation`, `service_router`, `client_router`, `client_route_name`, `icon`, `sort`)
VALUES
	(1, 0, '0,1', 'Root', 'page', NULL, NULL, NULL, NULL, 'Root', NULL, NULL, 0),
	(2, 1, '0,1,2', '首页', 'page', NULL, NULL, NULL, NULL, 'Home', NULL, NULL, 1),
	(3, 1, '0,1,3', '用户角色', 'page', NULL, NULL, NULL, NULL, 'User', NULL, NULL, 2),
	(4, 3, '0,1,3,4', '用户管理', 'page', NULL, NULL, NULL, NULL, 'UserManage', NULL, NULL, 0),
	(5, 4, '0,1,3,4,5', '用户列表', 'api', 'GET', 'UserManage', NULL, '/l/user', NULL, NULL, NULL, 0),
	(6, 4, '0,1,3,4,6', '用户详情', 'api', 'GET', NULL, 'read', '/l/user/{id}', NULL, NULL, NULL, 0),
	(7, 4, '0,1,3,4,7', '用户创建', 'api', 'POST', NULL, 'create', '/l/user', NULL, NULL, NULL, 0),
	(8, 4, '0,1,3,4,8', '用户编辑', 'api', 'PUT', NULL, 'update', '/l/user/{id}', NULL, NULL, NULL, 0),
	(9, 4, '0,1,3,4,9', '用户删除', 'api', 'DELETE', NULL, 'delete', '/l/user/{id}', NULL, NULL, NULL, 0),
	(10, 3, '0,1,3,10', '角色管理', 'page', NULL, NULL, NULL, NULL, 'UserRole', NULL, NULL, 0),
	(11, 10, '0,1,3,10,11', '角色列表', 'api', 'GET', 'UserRole', NULL, '/l/role', NULL, NULL, NULL, 0),
	(12, 10, '0,1,3,10,12', '角色详情', 'api', 'GET', NULL, 'read', '/l/role/{id}', NULL, NULL, NULL, 0),
	(13, 10, '0,1,3,10,13', '角色创建', 'api', 'POST', NULL, 'create', '/l/role', NULL, NULL, NULL, 0),
	(14, 10, '0,1,3,10,14', '角色编辑', 'api', 'PUT', NULL, 'update', '/l/role/{id}', NULL, NULL, NULL, 0),
	(15, 10, '0,1,3,10,15', '角色删除', 'api', 'DELETE', NULL, 'delete', '/l/role/{id}', NULL, NULL, NULL, 0),
	(16, 3, '0,1,3,16', '权限规则管理', 'page', NULL, NULL, NULL, NULL, 'UserPermission', NULL, NULL, 0),
	(17, 16, '0,1,3,16,17', '规则列表', 'api', 'GET', 'UserPermission', NULL, '/l/rule', NULL, NULL, NULL, 0),
	(18, 16, '0,1,3,16,18', '规则详情', 'api', 'GET', NULL, 'read', '/l/rule/{id}', NULL, NULL, NULL, 0),
	(19, 16, '0,1,3,16,19', '规则创建', 'api', 'POST', NULL, 'create', '/l/rule', NULL, NULL, NULL, 0),
	(20, 16, '0,1,3,16,20', '规则编辑', 'api', 'PUT', NULL, 'update', '/l/rule/{id}', NULL, NULL, NULL, 0),
	(21, 16, '0,1,3,16,21', '规则删除', 'api', 'DELETE', NULL, 'delete', '/l/rule/{id}', NULL, NULL, NULL, 0);
